#!/bin/sh
out=/run/motd.pacman
script=checkupdates

if [ -f "$out" ]
then
    echo
    echo "`cat "$out" | wc -l` packages can be updated"
    lastrun=`stat -c %Y "$out"` || lastrun=0
    expiration=`expr $lastrun + 3600`

    if [ `date +%s` -ge $expiration ]
    then
        $script > "$out" &
    fi
else
    $script > "$out" &
fi
